#!/bin/bash

echo "========================================="
echo "Langfuse Setup - Get API Keys"
echo "========================================="
echo ""
echo "1. Access Langfuse UI:"
echo "   http://localhost:3000"
echo ""
echo "2. Login with:"
echo "   Email: admin@kagent.local"
PASSWORD=$(kubectl get secret langfuse-secrets -n langfuse -o jsonpath='{.data.LANGFUSE_INIT_USER_PASSWORD}' | base64 -d)
echo "   Password: $PASSWORD"
echo ""
echo "3. Go to Settings → API Keys"
echo ""
echo "4. Copy the keys and run:"
echo ""
echo "   kubectl create secret generic langfuse-litellm-keys -n kagent \\"
echo "     --from-literal=LANGFUSE_PUBLIC_KEY='pk-lf-...' \\"
echo "     --from-literal=LANGFUSE_SECRET_KEY='sk-lf-...'"
echo ""
echo "========================================="
