apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: agent-core-terraform-{{ include "agent-core.name" . }}
  namespace: {{ include "agent-core.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "agent-core.labels" . | nindent 4 }}
spec:
  interval: 1m
  url: {{ .Values.global.terraformRepoUrl }}
  ref:
    branch: {{ .Values.global.terraformRepoRevision }}
