{{- if .Values.langfuse.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse-otel-keys
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  refreshInterval: "1h"
  target:
    name: langfuse-otel-keys
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LANGFUSE_OTEL_AUTH: |-
          {{`{{ printf "%s:%s" .publicKey .secretKey | b64enc }}`}}
  data:
    - secretKey: publicKey
      remoteRef:
        key: {{ .Values.langfuse.secretManagerKey }}
        property: LANGFUSE_PUBLIC_KEY
    - secretKey: secretKey
      remoteRef:
        key: {{ .Values.langfuse.secretManagerKey }}
        property: LANGFUSE_SECRET_KEY
{{- end }}
