apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: agentgateway-proxy
  namespace: agentgateway-system
spec:
  gatewayClassName: agentgateway
  listeners:
  - name: http
    port: {{ .Values.global.gatewayPort }}
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
