{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langfuse
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    {{- if contains "cloudfront.net" .Values.ingress.host }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    {{- end }}
    alb.ingress.kubernetes.io/healthcheck-path: /api/public/health
    argocd.argoproj.io/sync-wave: "10"
spec:
  ingressClassName: {{ .Values.ingress.className | default "platform" }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langfuse
                port:
                  number: 3000
{{- end }}
