global:
  awsRegion: us-west-2

image:
  repository: ghcr.io/berriai/litellm
  tag: main-stable
  pullPolicy: IfNotPresent

replicas: 1

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

settings:
  requestTimeout: 600
  rpmLimit: 100
  tpmLimit: 100000
  cache: false
