apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.podIdentity.serviceAccountName }}
  namespace: {{ .Values.podIdentity.namespace }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: agentcore-provider-runtime
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: {{ .Values.podIdentity.serviceAccountName }}
          containers:
            - name: package-runtime
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 512Mi
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-bedrockagentcore
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-bedrockagentcore:{{ .Values.provider.version }}
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: true
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: agentcore-provider-runtime
