apiVersion: v1
kind: Secret
metadata:
  name: kagent-openai
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  OPENAI_API_KEY: ""
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: bedrock-anthropic-claude-3-5-sonnet
  namespace: {{ .Release.Namespace }}
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  model: bedrock-claude-3-5-sonnet
  openAI:
    baseUrl: http://litellm-service.{{ .Release.Namespace }}.svc.cluster.local:4000
  provider: OpenAI
