{{- $values := .Values }}
{{- $syncPolicy := .Values.syncPolicy -}}
{{- $syncPolicyAppSet := .Values.syncPolicyAppSet -}}
{{- $repoURLGit := .Values.repoURLGit -}}
{{- $repoURLGitRevision := .Values.repoURLGitRevision -}}
{{- $repoURLGitBasePath := .Values.repoURLGitBasePath -}}
{{- $valueFiles := .Values.valueFiles -}}
{{- $valuesFilePrefix := .Values.valuesFilePrefix -}}
{{- $useValuesFilePrefix := (default false .Values.useValuesFilePrefix) -}}
{{- $useSelectors := .Values.useSelectors -}}
{{- $globalSelectors := .Values.globalSelectors -}}

{{- range $chartName, $chartConfig := .Values }}
{{- if and (kindIs "map" $chartConfig) (hasKey $chartConfig "enabled") }}
{{- if eq (toString $chartConfig.enabled) "true" }}
{{- $nameNormalize := printf "%s" $chartName | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $nameNormalize }}
  namespace: {{ default "argocd" $values.namespace }}
  annotations:
    {{- include "application-sets.annotations" $ | nindent 4 }}
    {{- if $chartConfig.annotationsAppSet }}{{- toYaml $chartConfig.annotationsAppSet | nindent 4 }}{{- end }}
  labels:
    {{- include "application-sets.labels" $ | nindent 4 }}
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  {{- if $chartConfig.syncPolicyAppSet }}
  syncPolicy:
  {{- toYaml $chartConfig.syncPolicyAppSet | nindent 4 }}
  {{- else }}
  syncPolicy:
  {{- toYaml $syncPolicyAppSet | nindent 4 }}
  {{- end }}
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            {{- if $globalSelectors }}
            {{- toYaml $globalSelectors | nindent 12 }}
            {{- end }}
          {{- if and $chartConfig.selector $useSelectors }}
          {{- toYaml $chartConfig.selector | nindent 10 }}
          {{- end }}
        {{- if not $chartConfig.path }}
        values:
          addonChart: {{ $chartConfig.chartName | default $nameNormalize | quote }}
          {{- if $chartConfig.defaultVersion }}
          addonChartVersion: {{ $chartConfig.defaultVersion | quote }}
          {{- end }}
          {{- if $chartConfig.chartRepository }}
          addonChartRepository: {{ $chartConfig.chartRepository | quote }}
          {{- end }}
          {{- if $chartConfig.chartNamespace }}
          addonChartRepositoryNamespace: {{ $chartConfig.chartNamespace | quote }}
          chart: {{ printf "%s/%s" $chartConfig.chartNamespace ($chartConfig.chartName | default $nameNormalize) | quote }}
          {{- else }}
          chart: {{ $chartConfig.chartName | default $nameNormalize | quote }}
          {{- end }}
        {{- end }}
  template:
    metadata:
      name: '{{ $nameNormalize }}-{{`{{ .name }}`}}'
    spec:
      project: default
      sources:
      - repoURL: {{ $repoURLGit | squote }}
        targetRevision: {{ $repoURLGitRevision | squote }}
        ref: values
        {{- if $chartConfig.path }}
      - repoURL: {{ $repoURLGit | squote }}
        path: {{ $chartConfig.path | squote }}
        targetRevision: {{ $repoURLGitRevision | squote }}
        {{- else }}
      - repoURL: '{{`{{ .values.addonChartRepository }}`}}'
        chart: '{{`{{ .values.chart }}`}}'
        targetRevision: '{{`{{ .values.addonChartVersion }}`}}'
        {{- end }}
        helm:
          releaseName: {{ default $nameNormalize $chartConfig.releaseName | squote }}
          ignoreMissingValueFiles: true
          {{- if $chartConfig.valuesObject }}
          valuesObject:
          {{- $chartConfig.valuesObject | toYaml | nindent 12 }}
          {{- end }}
          {{- if $valueFiles }}
          valueFiles:
          {{- include "application-sets.valueFiles" (dict
            "nameNormalize" ($chartConfig.chartName | default $nameNormalize)
            "chartConfig" $chartConfig
            "valueFiles" $valueFiles "values" $values) | nindent 12 }}
          {{- end }}
      destination:
        namespace: '{{ $chartConfig.namespace }}'
        name: '{{`{{ .name }}`}}'
      {{- if $chartConfig.syncPolicy }}
      syncPolicy:
        {{- toYaml $chartConfig.syncPolicy | nindent 8 }}
      {{- else }}
      syncPolicy:
        {{- toYaml $syncPolicy | nindent 8 }}
      {{- end }}
      {{- with $chartConfig.ignoreDifferences }}
      ignoreDifferences:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
